spring.datasource.url=jdbc:postgresql://dpg-d82qaorbc2fs73bf1kag-a.singapore-postgres.render.com/moneymanager_ocj6
spring.datasource.username=moneymanager_ocj6_user
spring.datasource.password= w6bjNWU3qDfM1m3wBGSDgSXHMKDlUhlX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
